services:
  _defaults:
    autowire: true
    autoconfigure: true

  Machine\EventStoreBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'

  Machine\EventStoreBundle\Service\RegisterHistoryEvent:
    tags: [machine.event_store.message_handler]

  Prooph\EventStore\EventStore: '@app.event_store.default'

  Machine\EventStoreBundle\Infrastructure\Repository\EventStoreHistory:
    arguments:
      - '@app.event_store.default'

  app.event_store.default:
    class: Prooph\EventStore\Pdo\MySqlEventStore
    arguments:
      - '@Machine\EventStoreBundle\Factory\EventStoreMessageFactory'
      - '@app.event_store.pdo_connection.mysql'
      - '@app.event_store.mysql.persistence_strategy'

  app.event_store.pdo_connection.mysql:
    class: \PDO
    arguments:
      - '%env(MYSQL_DSN)%'
      - '%env(MYSQL_USER)%'
      - '%env(MYSQL_PASSWORD)%'

  app.event_store.mysql.persistence_strategy:
    class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

  Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: null
